apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      myappkey: myappvalue
  template:
    metadata:
      labels:
        myappkey: myappvalue
    spec:
      containers:
        - name: myapp-container
          image: newts/myapp
          ports:
            - containerPort: 8000