name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
      - run: pwd
      - run: go test ./main.go
        working-directory: ./
